# Generated by Django 4.2.2 on 2023-11-07 21:25
import json
import os

from django.db import migrations


def load_banks(apps, schema_editor):
    """
    Pre-load banks info in db

    :param apps: app registry
    :param schema_editor: schema editor
    :return: None
    """

    # Load banks from JSON
    banks_file_path = os.path.join(os.path.dirname(__file__), "..", "..", "resources", "banks", "fr_banks.json")
    with open(banks_file_path, 'r', encoding="utf8") as banks_info:
        banks = json.load(banks_info)

    # Retrieve model from app
    bank_model = apps.get_model('dashboard', 'Bank')

    # For each bank create a new object in db
    for bank, info in banks.items():
        bank_model.objects.create(
            name=bank,
            swift=info.get("swift"),
            bic=info.get("bic")
        )


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0013_alter_bank_logo"),
    ]

    operations = [
        migrations.RunPython(load_banks),
    ]
